### ISSUE TITLE
Equations 6.4 and 6.5

### ISSUE THREAD

**Issue by MaximeBouton** [sisl/dmubook-errata#1]
In equations 6.4 and 6.5, shouldn't $O(o \mid s')$ be replaced by $O(o \mid s', a)$ ?

**Comment by mykelk** [comment]
Not really. Fig. 6.2 does not have a dependency on action and the first sentence of Sec. 6.1.2 has O(o | s), though the next sentence says that we can add a dependency on a if we want to.
