### ISSUE TITLE
Sec 4.7.3 notation consistency

### ISSUE THREAD

**Issue by rbalexander1** [sisl/dmubook-errata#3]
(4th ed.) In Section 4.7.3 (Cross Entropy Methods) under the bullet for "_Sample_.", I think we should have $P(\lambda \mid \theta)$ instead of $P(\lambda ; \theta)$ to keep consistency with the notation in Eq. 4.40 and Alg. 4.12. There is another instance of this in the legend for Fig. 4.12.

It looks like some other cases of this were resolved in previous printings - these ones may just have gotten left behind!

**Comment by mykelk** [comment]
Thanks!
